### ISSUE TITLE
Updating your endpoints for The Graph

### ISSUE THREAD

**Issue by alex-pakalniskis** [ALMIGHTYABE/Thena-Data#2]
Hey @ALMIGHTYABE 

I'm Alex, a product manager at Edge & Node working on The Graph. I noticed that your project references Hosted Service endpoints. In case you haven't heard yet I wanted to let you know that Hosted Service endpoints will not be available starting in June: https://thegraph.com/blog/sunbeam-upgrade-window/

Please upgrade your subgraph to the decentralized network to enjoy uninterrupted access for all your data scraping needs. 

Thanks and let me know if you have any questions (I also noticed you reference hosted service in this repo: https://github.com/ALMIGHTYABE/Retro-Data)

Best,
Alex

**Comment by ALMIGHTYABE** [comment]
Resolved on Thena.
